### ISSUE TITLE
Building a reusable microservice platform

### ISSUE THREAD

**Issue by redowl3** [horsdal/microservices-in-dotnetcore#1]
This could entirely be our fault, but when trying to use the reusable platform in Chapter 11 we are encountering an error, any help appreciated.  We are using VS2017 RC2 and net core 1.1.

11:41:17 [Error] () Unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at MicroserviceNET.Auth.Authorization.<>c__DisplayClass0_0.<Middleware>b__0(IDictionary`2 env)
   at MicroserviceNET.Logging.MonitoringMiddleware.Invoke(IDictionary`2 env)
   at MicroserviceNET.Logging.PerformanceLogging.<>c__DisplayClass0_0.<<Middleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MicroserviceNET.Logging.RequestLogging.<>c__DisplayClass0_0.<<Middleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MicroserviceNET.Logging.CorrelationToken.<>c__DisplayClass0_0.<<Middleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MicroserviceNET.Logging.GlobalErrorLogging.<>c__DisplayClass0_0.<<Middleware>b__0>d.MoveNext()

**Comment by horsdal** [comment]
I think the problem stems from requests that do not have the appropriate auth headers set. 
In the `Startup` of `HelloMicroservicesPlatform` this code appears:

```
      app.UseOwin()
         .UseMonitoringAndLogging(ConfigureLogger(), HealthCheck)
         .UseAuthPlatform("test-scope")
         .UseNancy();
```
The important bit here is the `UseAuthPlatform("test-scope")` line which configures the auth middleware to require all requests to have an auth header and have the scope `test-scope`.
Unfortunately the auth middleware throws when there is no auth header instead of failing the request in a controlled manner. The bug is in line 18 of `AuthorizationMiddleware.cs`, which looks like this:
```
        if (principal.HasClaim("scope", requiredScope))
```
When there is no auth header `principal` is null. Boom.
To fix it change that line to 
```
        if (principal != null && principal.HasClaim("scope", requiredScope))
```
Now you should get a proper `403` response when there are no auth headers.

Also worth noting is that the sample code in chapter 11 takes some fiddling to run because of the requirement for auth headers. -It's really more of an illustration than a ready to run solution.
You might consider taking out the auth platform bit and then see the other parts of the platform in action - that is the request logging, performance logging and monitor endpoints.

**Comment by redowl3** [comment]
Thanks for the update.  Do you have an example request including auth headers and scope that we can try?
